### ISSUE TITLE
Yowsup have update v3, please update this framework

### ISSUE THREAD

**Issue by Sharissa90** [danielcardeenas/whatsapp-framework#265]
Hi, I notice that yowsup have update their library to v3, this version use noise protocol so it fix some problem that raised lately. please update this framework, I tried just update yowsup v3 only, but many errors raised, I believe yowsup made some changes in their function so this framework need little adjustment to make it work.. 

Thank you for your great jobs make this framework easier to implemented yowsup

**Comment by itsVKT** [comment]
Yes please update the framework

**Comment by AmitGamingKing** [comment]
@danielcardeenas yes we need you to reply on this thread ASAP! Because even though Yowsup is updated we can't use this framework due to protocol changes...

**Comment by devalexanderdaza** [comment]
Because we did not help Daniel, and together we started to mount the compatibility of the library again?

**Comment by elchory96** [comment]
I already managed to solve so that the bot receives messages again, and sends them.

As I saw it, in run.py touch comment the line:

```
# except AuthError as e:
         # print ("Auth Error, reason% s"% e)
```

Because the AuthError library no longer exists in from yowsup.layers.auth

The 

> sudo ./setup.sh

 of this repository should not be used since it will be installing the old version of yowsup that Daniel Cardenas has.

Therefore, you must first run the command 

> pip3 install yowsup

 then install the library 

> pip3 install pycrypto

 and 

> pip3 install blinker

Then when registering the number with the command

> # Replace CC with your country code (See https://countrycode.org)
> yowsup-cli registration --requestcode sms --phone CCXXXXXXXX --cc CC -E Android
> # After getting the sms code (in this example: 123456)
> yowsup-cli registration --register 123456 --phone CCXXXXXXXX --cc CC -E Android

the password does not exist anymore, now there is one called 

> client_static_keypair

 which would be the **new password**, which is what you must add to the config.py.

I will continue reviewing possible problems. I will be updating this issue

**Comment by elchory96** [comment]
> TypeError: pushDefaultLayers() takes 1 positional argument but 2 were given

Remove parameter in line 24 of run.py

OLD

> .pushDefaultLayers(encryption)\

NEW

> .pushDefaultLayers()\

**Comment by Sharissa90** [comment]
Thank you @elchory96 I can running this framework again, but can you solve how to send image? I tried but always failed to send image

**Comment by elchory96** [comment]
What error do you get?

**Comment by AmitGamingKing** [comment]
Yes @elchory96 media sending is not working I mean I didn't try it on this framework I tried on terminal yowsup demos `/image send <number> <location>` and I got `RequestUploadError` something like that

**Comment by AmitGamingKing** [comment]
Also I tried all things step by step but getting error after starting Mac
```
[Whatsapp] Mac started

W 2019-04-24 00:11:54,612 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
Traceback (most recent call last):
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_socket.py", line 42, in connectAndLoop
    self.connectionCallbacks.onRecvData(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 82, in onRecvData
    self.receive(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 85, in receive
    self.toUpper(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 149, in receive
    self._flush_incoming_buffer()
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 19, in receive
    node = self.reader.getProtocolTreeNode(bytearray(data))
  File "/home/amitgamingking/.local/lib/python3.6/site-packages/yowsup/layers/coder/decoder.py", line 11, in getProtocolTreeNode
    raise ValueError("deflate payloads are not supported")
ValueError: deflate payloads are not supported
E 2019-04-24 00:11:55,288 yowsup.layers.network.dispatcher.dispatcher_socket - deflate payloads are not supported
```

**Comment by jesusvalverde** [comment]
Onto @Ubuntu 
Done all "new" instlation procedure.

[Whatsapp] Mac started

W 2019-04-23 15:56:15,471 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/network/dispatcher/dispatcher_socket.py", line 42, in connectAndLoop
    self.connectionCallbacks.onRecvData(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 82, in onRecvData
    self.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/network/layer.py", line 85, in receive
    self.toUpper(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
    self.toUpper(bytes(data))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 149, in receive
    self._flush_incoming_buffer()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/noise/layer.py", line 137, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 36, in receive
    self.onMessage(protocolTreeNode)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 69, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 81, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/layers/axolotl/layer_receive.py", line 118, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/axolotl/manager.py", line 164, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 37, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yowsup/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!
E 2019-04-23 15:56:15,476 yowsup.layers.network.dispatcher.dispatcher_socket - No such prekeyRecord!

**Comment by Sharissa90** [comment]
bot will crash if receiving media file, any idea how ignore this type of message temporary before yowsup update their code?

**Comment by AmitGamingKing** [comment]
@Sharissa90 are you able to run bot normally for receiving and sending text messages?

**Comment by jesusvalverde** [comment]
> @Sharissa90 are you able to run bot normally for receiving and sending text messages?

Able to send and recived....

**Comment by jesusvalverde** [comment]
> bot will crash if receiving media file, any idea how ignore this type of message temporary before yowsup update their code?

Error on reciving one image 

AttributeError: 'ImageDownloadableMediaMessageProtocolEntity' object has no attribute 'getMediaKey'
E 2019-04-24 14:30:31,109 yowsup.layers.network.dispatcher.dispatcher_socket - 'ImageDownloadableMediaMessageProtocolEntity' object has no attribute 'getMediaKey'

**Comment by jesusvalverde** [comment]
Not able to send Images....seems to be a thing from youwsup 3

**Comment by Sharissa90** [comment]
> 
> 
> @Sharissa90 are you able to run bot normally for receiving and sending text messages?

yes, but not stable like yowsup2. sometimes it crashing, I think yowsup V3 still buggy

**Comment by Sharissa90** [comment]
I have trick to solve bot crashing on receiving media file, edit file app/layer.py find @ProtocolEntityCallback("message") and edit like this

@ProtocolEntityCallback("message")
    def on_message(self, message_entity):
        mac.receive_message(self, message_entity)
        if message_entity.getType() == 'text':
            message = Message(message_entity)
            if message.valid:
                signals.message_received.send(message)
                if helper.is_command(message.message):
                    signals.command_received.send(message)
        elif message_entity.getType() == 'media':
            pass
            #    if message_entity.getMediaType() == "location":
            # message = Message(message_entity)
            # if message.valid:
            #     signals.message_received.send(message)
            # if hasattr(message_entity, 'getMediaType'):
            #     self.onMediaMessage(message_entity)
        mac.disconnect(self)

**Comment by gabrieru** [comment]
> **sword**, which is what you must add to the config.py.
> 
> I will continue reviewing possible problems. I will be updating this iss

hello, i am newbie on this, i ran the commands of library into whatsapp framework but it wont taking my phone number, just giving me errors, first when i try to register with:
yowsup-cli registration --requestcode sms --phone CCXXXXXXXX --cc CC -E Android

it says must be with "android" without uppercase, but when i run it this gives me many errors

**Comment by AmitGamingKing** [comment]
Still waiting for update no response for @danielcardeenas :(

**Comment by devalexanderdaza** [comment]
Hello, seeing that @danielcardeenas  has not appeared, I decided to start a new hybrid project between yowsup3 and whatsapp-framework. Although the installation of yowsup3 does not generate errors, and the first connection with whatsapp is established correctly, there are errors that I think the community can help solve.

The repository link is: https://github.com/devalexanderdaza/yowsapp-framework

**Comment by Sharissa90** [comment]
@devalexanderdaza do you able send image?

**Comment by devalexanderdaza** [comment]
> @devalexanderdaza puedes enviar la imagen?

In a while I will create an incidence in the repository to manage the support of the community. Follow the instructions contained in the repository so that you can reach the error and between all of us we can solve it and use the library again

**Comment by jesusvalverde** [comment]
Update 
yowsup-cli v3.2.0
yowsup v3.2.3

Made the modificacion on top and .... got this error  

Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from app.layer import MacLayer
  File "/home/ubuntu/whatsapp-framework/app/__init__.py", line 1, in <module>
    import modules
  File "/home/ubuntu/whatsapp-framework/modules/__init__.py", line 1, in <module>
    from modules import start
  File "/home/ubuntu/whatsapp-framework/modules/start.py", line 2, in <module>
    from app.mac import mac, signals
  File "/home/ubuntu/whatsapp-framework/app/mac/mac.py", line 14, in <module>
    from yowsup.common.optionalmodules import PILOptionalModule, AxolotlOptionalModule
ImportError: cannot import name 'AxolotlOptionalModule'


used to work with yowsup v3.0

**Comment by jesusvalverde** [comment]
nano app/mac/mac.py

delete 'AxolotlOptionalModule' 
from yowsup.common.optionalmodules import PILOptionalModule

nano app/utils/downloader.py
comment
#from yowsup.layers.protocol_media.mediadownloader import MediaDownloader

#return MediaDownloader().download(url.decode('ASCII'))
sudo  app/layer.py

comment
#from yowsup.layers.protocol_media.mediadownloader import MediaDownloader

sudo ./clean.sh 

./start.sh

but Errors 

line 63, in on_auth
    assert type(local_static) is KeyPair



yowsup-cli v3.2.0
yowsup v3.2.3

**Comment by navasonline2015** [comment]
@Gabrieru, 
U need to provide your country code in place of CC.

**Comment by wisrovi** [comment]
Hi,

I installed the next packages in my raspberry with pip3:
-python-axolotl
-protobuf
-six
-argparse 
-readline 
-pillow 
-tqdm 
-requests 
-yowsup
-pycrypto
-blinker

next, I download your repository (today is 2019-May-17) and intent send the registration with:
yowsup-cli registration --requestcode sms --phone 57317509xxx --cc 57 -E android

but the console print a error:

Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/EGG-INFO/scripts/yowsup-cli", line 198, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "/usr/local/lib/python3.5/dist-packages/yowsup/registration/__init__.py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "/usr/local/lib/python3.5/dist-packages/yowsup/registration/coderequest.py", line 1, in <module>
    from yowsup.common.http.warequest import WARequest
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/http/__init__.py", line 2, in <module>
    from .warequest import WARequest
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/http/warequest.py", line 8, in <module>
    from yowsup.common.tools import WATools
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/tools.py", line 10, in <module>
    from consonance.structs.keypair import KeyPair
  File "/usr/local/lib/python3.5/dist-packages/consonance/structs/keypair.py", line 4, in <module>
    from dissononce.dh.x25519.x25519 import X25519DH
  File "/usr/local/lib/python3.5/dist-packages/dissononce/dh/x25519/x25519.py", line 1, in <module>
    from cryptography.hazmat.primitives.asymmetric import x25519
ImportError: cannot import name 'x25519'

#could help me, please?

**Comment by Sharissa90** [comment]
> yowsup-cli registration --requestcode sms --phone 57317509xxx --cc 57 -E android

@wisrovi just type 
yowsup-cli registration --requestcode sms --config-phone 57317509xxx --cc 57

**Comment by wisrovi** [comment]
ok, I executed this:
yowsup-cli registration --requestcode sms --config-phone 57317509xxx --cc 57


But the console printed:
usage: registration [-h] [-v] [-d] [--help-config] [-c CONFIG] [-E {android}]
                    [-m MCC] [-n MNC] [-p PHONE] [-C CC]
                    [-r (sms|voice) | -R code]
registration: error: unrecognized arguments: --config-phone 57317509xxxx

**Comment by gabrieru** [comment]
someone got it working? i can pay for that if can help me to fix

**Comment by Sharissa90** [comment]
> 
> 
> ok, I executed this:
> yowsup-cli registration --requestcode sms --config-phone 57317509xxx --cc 57
> 
> But the console printed:
> usage: registration [-h] [-v] [-d] [--help-config] [-c CONFIG] [-E {android}]
> [-m MCC] [-n MNC] [-p PHONE] [-C CC]
> [-r (sms|voice) | -R code]
> registration: error: unrecognized arguments: --config-phone 57317509xxxx
> 
> The version for youwsup version -v is:
> yowsup-cli v2.0.15
> Using yowsup v3.2.3

my mistake use --config-cc not just --cc

yowsup-cli registration --requestcode sms --config-phone 57317509xxx --config-cc 57

**Comment by wisrovi** [comment]
I tried this:
yowsup-cli registration --requestcode sms --config-phone 57317509xxxx --config-cc 57

but, The console:
error: unrecognized arguments: --config-phone 573175098360 --config-cc 57

could could help me, please?

Thanks a lot

**Comment by Sharissa90** [comment]
> 
> 
> I tried this:
> yowsup-cli registration --requestcode sms --config-phone 57317509xxxx --config-cc 57
> 
> but, The console:
> error: unrecognized arguments: --config-phone 573175098360 --config-cc 57
> 
> could could help me, please?
> 
> Thanks a lot

dont using latest yowsup from master, this master using profile.. using yowsup release instead

**Comment by devalexanderdaza** [comment]
Hi guys... I have released the first stable version of the fully functional Yowsapp Framework. I invite you to help the community grow and do not forget to give a star to the repository

[Yowsapp Framework](https://github.com/devalexanderdaza/yowsapp-framework)

**Comment by pablofuentes88** [comment]
Ya no se que hacer. Lo ultimo que hizo fue desinstalar el yowup he instalar el que instaló @devalexanderdaza , pero cuando le doy ./start en la carpeta ~/whatsapp-framework me genera este error:   

````
Traceback (most recent call last):
  File "run.py", line 3, in `<module>`
    from yowsup.layers.auth import AuthError
ImportError: cannot import name 'AuthError'
Whatsapp bot crashed with code 1.  Respawning..
````
Alguien me hecha un cable?? de antemano muchas gracias, PD: Estoy usando Ubuntu Server 18

**Comment by marlos7** [comment]
Looks like has been discontinued, there's a good project I'm using!
https://github.com/jonalan7/Hydra-bot
